# Feature scaling with sklearn - Exercise Solved

You are given a real estate dataset. 

Real estate is one of those examples that every regression course goes through as it is extremely easy to understand and there is a (almost always) certain causal relationship to be found.

The data is located in the file: 'real_estate_price_size_year.csv'. 

You are expected to create a multiple linear regression, using the new data.  
This time, however, **please standardize the data**.

Apart from that, please:
-  Display the intercept and coefficient(s)
-  Find the R-squared and Adjusted R-squared
-  Compare the R-squared and the Adjusted R-squared
-  Compare the R-squared of this regression and the simple linear regression where only 'size' was used
-  Using the model make a prediction about an apartment with size 750 sq.ft. from 2009
-  Find the univariate (or multivariate if you wish - see the article) p-values of the two variables. What can you say about them?
-  Create a summary table with your findings

In this exercise, the dependent variable is 'price', while the independent variables are 'size' and 'year'.

Good luck!

## Import the relevant libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

## Load the data

In [2]:
est_data = pd.read_csv('real_estate_price_size_year.csv')
est_data

price     size  year
0   234314.144   643.09  2015
1   228581.528   656.22  2009
2   281626.336   487.29  2018
3   401255.608  1504.75  2015
4   458674.256  1275.46  2009
..         ...      ...   ...
95  252460.400   549.80  2009
96  310522.592  1037.44  2009
97  383635.568  1504.75  2006
98  225145.248   648.29  2015
99  274922.856   705.29  2006

[100 rows x 3 columns]

In [3]:
est_data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [4]:
est_data.describe()

price         size         year
count     100.000000   100.000000   100.000000
mean   292289.470160   853.024200  2012.600000
std     77051.727525   297.941951     4.729021
min    154282.128000   479.750000  2006.000000
25%    234280.148000   643.330000  2009.000000
50%    280590.716000   696.405000  2015.000000
75%    335723.696000  1029.322500  2018.000000
max    500681.128000  1842.510000  2018.000000

## Create the regression

### Declare the dependent and the independent variables

In [9]:
x = est_data[['size','year']]
y = est_data['price']

### Scale the inputs

In [11]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
scale.fit(x)
x_scaled = scale.transform(x)

### Regression

In [13]:
reg_ = LinearRegression()
reg_.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### Find the intercept

In [15]:
reg_.intercept_

292289.4701599997

### Find the coefficients

In [16]:
reg_.coef_

array([67501.57614152, 13724.39708231])

### Calculate the R-squared

In [17]:
reg_.score(x_scaled,y)

0.7764803683276793

### Calculate the Adjusted R-squared

In [19]:
def adjusted_r_sq(x, y):
    r2 = reg.score(x,y)
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r_sq = 1-(1-r2)*(n-1)/(n-p-1)
    
    return adjusted_r_sq

In [20]:
adjusted_r_sq(x_scaled, y)

0.77187171612825

### Making predictions

Find the predicted price of an apartment that has a size of 750 sq.ft. from 2009.

In [24]:
new_values = [[750,2009]]
new_values_scaled = scale.transform(new_values)

reg.predict(new_values_scaled)

array([258330.34465995])

### Calculate the univariate p-values of the variables

In [25]:
from sklearn.feature_selection import f_regression

In [26]:
f_regression(x_scaled,y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [27]:
p_values = f_regression(x,y)[1].round(2)

In [28]:
p_values

array([0.  , 0.36])

### Create a summary table with your findings

In [29]:
summary = pd.DataFrame(data = x.columns.values, columns=['Features'])
summary ['Coefficients'] = reg_.coef_
summary ['p-values'] = p_values.round(3)
summary

Features  Coefficients  p-values
0     size  67501.576142      0.00
1     year  13724.397082      0.36