# Multiple Linear Regression with sklearn - Exercise Solved

You are given a real estate dataset. 

Real estate is one of those examples that every regression course goes through as it is extremely easy to understand and there is a (almost always) certain causal relationship to be found.

The data is located in the file: 'real_estate_price_size_year.csv'. 

You are expected to create a multiple linear regression, using the new data. 

Apart from that, please:
-  Display the intercept and coefficient(s)
-  Find the R-squared and Adjusted R-squared
-  Compare the R-squared and the Adjusted R-squared
-  Compare the R-squared of this regression and the simple linear regression where only 'size' was used
-  Using the model make a prediction about an apartment with size 750 sq.ft. from 2009
-  Find the univariate (or multivariate if you wish - see the article) p-values of the two variables. What can you say about them?
-  Create a summary table with your findings

In this exercise, the dependent variable is 'price', while the independent variables are 'size' and 'year'.

Good luck!

## Import the relevant libraries

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

## Load the data

In [16]:
est_data = pd.read_csv('real_estate_price_size_year.csv')
est_data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [17]:
est_data

price     size  year
0   234314.144   643.09  2015
1   228581.528   656.22  2009
2   281626.336   487.29  2018
3   401255.608  1504.75  2015
4   458674.256  1275.46  2009
..         ...      ...   ...
95  252460.400   549.80  2009
96  310522.592  1037.44  2009
97  383635.568  1504.75  2006
98  225145.248   648.29  2015
99  274922.856   705.29  2006

[100 rows x 3 columns]

## Create the regression

### Declare the dependent and the independent variables

In [18]:
y = est_data['price']
x = est_data[['size','year']]

### Regression

In [19]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### Find the intercept

In [20]:
reg.intercept_

-5772267.017463277

### Find the coefficients

In [21]:
reg.coef_

array([ 227.70085401, 2916.78532684])

### Calculate the R-squared

In [22]:
reg.score(x,y)

0.7764803683276792

### Calculate the Adjusted R-squared

In [23]:
def adjusted_r_sq(x, y):
    r2 = reg.score(x,y)
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r_sq = 1-(1-r2)*(n-1)/(n-p-1)
    
    return adjusted_r_sq

In [24]:
adjusted_r_sq(x, y)

0.7718717161282499

### Making predictions

Find the predicted price of an apartment that has a size of 750 sq.ft. from 2009.

In [25]:
reg.predict([[750,2009]])

array([258330.34465995])

### Calculate the univariate p-values of the variables

In [26]:
from sklearn.feature_selection import f_regression
f_regression(x,y)[1].round(2)

array([0.  , 0.36])

### Create a summary table with your findings

In [14]:
summary = pd.DataFrame(data = x.columns.values, columns=['Features'])
summary ['Coefficients'] = reg.coef_
p = f_regression(x,y)[1].round(2)
summary ['p-values'] = p
summary

Features  Coefficients  p-values
0     size    227.700854      0.00
1     year   2916.785327      0.36